apiVersion: v1
kind: Service
metadata:
  name: {{ include "krabka-schema-registry.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels: {{- include "krabka-schema-registry.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 8081
      targetPort: rest
      protocol: TCP
      name: rest
  selector: {{- include "krabka-schema-registry.selectorLabels" . | nindent 4 }}
